# Generated by Django 2.2 on 2019-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0003_auto_20190612_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualanmodel',
            name='bulan_transaksi',
            field=models.CharField(max_length=200),
        ),
    ]
