# Generated by Django 2.2 on 2019-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0005_auto_20190617_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualanmodel',
            name='pendapatan',
            field=models.IntegerField(default=0),
        ),
    ]
