# Generated by Django 2.2 on 2019-06-27 18:10

import django.core.validators
from django.db import migrations, models
import input_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0006_penjualanmodel_pendapatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualanmodel',
            name='bulan_transaksi',
            field=models.CharField(choices=[('januari', 'Januari'), ('februari', 'Februari'), ('maret', 'Maret'), ('april', 'April'), ('mei', 'Mei'), ('juni', 'Juni'), ('juli', 'Juli'), ('agustus', 'Agustus'), ('september', 'September'), ('oktober', 'Oktober'), ('november', 'November'), ('desember', 'Desember')], default='Januari', max_length=200),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jasa_pembersih_air',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jasa_pembersih_cooling_tower',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jasa_pembersih_kerak_sillica',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jasa_pembersih_stp',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C441',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C442',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C443',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C451',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C452',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C453',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C461',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C462',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_C463',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_abf',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_apartemen',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_asam_sulfat',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_hcl',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_hotel',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_mall',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='jumlah_molases',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='pendapatan',
            field=models.IntegerField(default=0, validators=[input_data.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='penjualanmodel',
            name='tahun_transaksi',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2009), input_data.models.max_value_current_year]),
        ),
    ]
