# Generated by Django 2.2 on 2019-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingPenjualanModel',
            fields=[
                ('id_penjualan', models.AutoField(primary_key=True, serialize=False)),
                ('bulan_transaksi', models.CharField(max_length=200)),
                ('tahun_transaksi', models.IntegerField(default=2010)),
                ('jumlah_hotel', models.IntegerField(default=0)),
                ('jumlah_mall', models.IntegerField(default=0)),
                ('jumlah_apartemen', models.IntegerField(default=0)),
                ('jumlah_C441', models.IntegerField(default=0)),
                ('jumlah_C442', models.IntegerField(default=0)),
                ('jumlah_C443', models.IntegerField(default=0)),
                ('jumlah_C451', models.IntegerField(default=0)),
                ('jumlah_C452', models.IntegerField(default=0)),
                ('jumlah_C453', models.IntegerField(default=0)),
                ('jumlah_C461', models.IntegerField(default=0)),
                ('jumlah_C462', models.IntegerField(default=0)),
                ('jumlah_C463', models.IntegerField(default=0)),
                ('jasa_pembersih_air', models.IntegerField(default=0)),
                ('jasa_pembersih_kerak_sillica', models.IntegerField(default=0)),
                ('jasa_pembersih_cooling_tower', models.IntegerField(default=0)),
                ('jasa_pembersih_stp', models.IntegerField(default=0)),
                ('jumlah_asam_sulfat', models.IntegerField(default=0)),
                ('jumlah_molases', models.IntegerField(default=0)),
                ('jumlah_hcl', models.IntegerField(default=0)),
                ('jumlah_abf', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
